using System;
using Xunit;

namespace KWLEC200Test
{
    #region Using Directives

    using System.Globalization;

    using Microsoft.Extensions.Logging;

    using Xunit;
    using Xunit.Abstractions;
    using Xunit.Logger;

    using KWLEC200Lib;

    #endregion

    /// <summary>
    /// XUnit testing class.
    /// </summary>
    [Collection("KWLEC200 Test Collection")]
    public class TestData : IClassFixture<KWLEC200Fixture>
    {
        #region Private Data Members

        private readonly ILogger<KWLEC200> _logger;
        private readonly IKWLEC200 _kwlec200;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        /// <param name="outputHelper"></param>
        public TestData(KWLEC200Fixture fixture, ITestOutputHelper outputHelper)
        {
            // Set the default culture.
            CultureInfo.CurrentCulture = new CultureInfo("en-US");

            var loggerFactory = new LoggerFactory();
            loggerFactory.AddProvider(new XunitLoggerProvider(outputHelper));
            _logger = loggerFactory.CreateLogger<KWLEC200>();

            _kwlec200 = fixture.KWLEC200;
        }

        #endregion

        #region Test Methods

        [Theory]
        [InlineData("KWLEC200.Data")]
        [InlineData("KWLEC200.Data.ItemDescription")]
        [InlineData("KWLEC200.Data.OrderNumber")]
        [InlineData("KWLEC200.Data.MacAddress")]
        [InlineData("KWLEC200.Data.Language")]
        [InlineData("KWLEC200.Data.Date")]
        [InlineData("KWLEC200.Data.Time")]
        [InlineData("KWLEC200.Data.DayLightSaving")]
        [InlineData("KWLEC200.Data.AutoUpdateEnabled")]
        [InlineData("KWLEC200.Data.PortalAccessEnabled")]
        [InlineData("KWLEC200.Data.ExhaustVentilatorVoltageLevel1")]
        [InlineData("KWLEC200.Data.SupplyVentilatorVoltageLevel1")]
        [InlineData("KWLEC200.Data.ExhaustVentilatorVoltageLevel2")]
        [InlineData("KWLEC200.Data.SupplyVentilatorVoltageLevel2")]
        [InlineData("KWLEC200.Data.ExhaustVentilatorVoltageLevel3")]
        [InlineData("KWLEC200.Data.SupplyVentilatorVoltageLevel3")]
        [InlineData("KWLEC200.Data.ExhaustVentilatorVoltageLevel4")]
        [InlineData("KWLEC200.Data.SupplyVentilatorVoltageLevel4")]
        [InlineData("KWLEC200.Data.MinimumVentilationLevel")]
        [InlineData("KWLEC200.Data.KwlBeEnabled")]
        [InlineData("KWLEC200.Data.KwlBecEnabled")]
        [InlineData("KWLEC200.Data.DeviceConfiguration")]
        [InlineData("KWLEC200.Data.PreheaterStatus")]
        [InlineData("KWLEC200.Data.KwlFTFConfig0")]
        [InlineData("KWLEC200.Data.KwlFTFConfig1")]
        [InlineData("KWLEC200.Data.KwlFTFConfig2")]
        [InlineData("KWLEC200.Data.KwlFTFConfig3")]
        [InlineData("KWLEC200.Data.KwlFTFConfig4")]
        [InlineData("KWLEC200.Data.KwlFTFConfig5")]
        [InlineData("KWLEC200.Data.KwlFTFConfig6")]
        [InlineData("KWLEC200.Data.KwlFTFConfig7")]
        [InlineData("KWLEC200.Data.HumidityControlStatus")]
        [InlineData("KWLEC200.Data.HumidityControlTarget")]
        [InlineData("KWLEC200.Data.HumidityControlStep")]
        [InlineData("KWLEC200.Data.HumidityControlStop")]
        [InlineData("KWLEC200.Data.CO2ControlStatus")]
        [InlineData("KWLEC200.Data.CO2ControlTarget")]
        [InlineData("KWLEC200.Data.CO2ControlStep")]
        [InlineData("KWLEC200.Data.VOCControlStatus")]
        [InlineData("KWLEC200.Data.VOCControlTarget")]
        [InlineData("KWLEC200.Data.VOCControlStep")]
        [InlineData("KWLEC200.Data.ThermalComfortTemperature")]
        [InlineData("KWLEC200.Data.TimeZoneOffset")]
        [InlineData("KWLEC200.Data.DateFormat")]
        [InlineData("KWLEC200.Data.HeatExchangerType")]
        [InlineData("KWLEC200.Data.PartyOperationDuration")]
        [InlineData("KWLEC200.Data.PartyVentilationLevel")]
        [InlineData("KWLEC200.Data.PartyOperationRemaining")]
        [InlineData("KWLEC200.Data.PartyOperationActivate")]
        [InlineData("KWLEC200.Data.StandbyOperationDuration")]
        [InlineData("KWLEC200.Data.StandbyVentilationLevel")]
        [InlineData("KWLEC200.Data.StandbyOperationRemaining")]
        [InlineData("KWLEC200.Data.StandbyOperationActivate")]
        [InlineData("KWLEC200.Data.OperationMode")]
        [InlineData("KWLEC200.Data.VentilationLevel")]
        [InlineData("KWLEC200.Data.VentilationPercentage")]
        [InlineData("KWLEC200.Data.TemperatureOutdoor")]
        [InlineData("KWLEC200.Data.TemperatureSupply")]
        [InlineData("KWLEC200.Data.TemperatureExhaust")]
        [InlineData("KWLEC200.Data.TemperatureExtract")]
        [InlineData("KWLEC200.Data.TemperaturePreHeater")]
        [InlineData("KWLEC200.Data.TemperaturePostHeater")]
        [InlineData("KWLEC200.Data.ExternalHumiditySensor1")]
        [InlineData("KWLEC200.Data.ExternalHumiditySensor2")]
        [InlineData("KWLEC200.Data.ExternalHumiditySensor3")]
        [InlineData("KWLEC200.Data.ExternalHumiditySensor4")]
        [InlineData("KWLEC200.Data.ExternalHumiditySensor5")]
        [InlineData("KWLEC200.Data.ExternalHumiditySensor6")]
        [InlineData("KWLEC200.Data.ExternalHumiditySensor7")]
        [InlineData("KWLEC200.Data.ExternalHumiditySensor8")]
        [InlineData("KWLEC200.Data.ExternalHumidityTemperature1")]
        [InlineData("KWLEC200.Data.ExternalHumidityTemperature2")]
        [InlineData("KWLEC200.Data.ExternalHumidityTemperature3")]
        [InlineData("KWLEC200.Data.ExternalHumidityTemperature4")]
        [InlineData("KWLEC200.Data.ExternalHumidityTemperature5")]
        [InlineData("KWLEC200.Data.ExternalHumidityTemperature6")]
        [InlineData("KWLEC200.Data.ExternalHumidityTemperature7")]
        [InlineData("KWLEC200.Data.ExternalHumidityTemperature8")]
        [InlineData("KWLEC200.Data.ExternalCO2Sensor1")]
        [InlineData("KWLEC200.Data.ExternalCO2Sensor2")]
        [InlineData("KWLEC200.Data.ExternalCO2Sensor3")]
        [InlineData("KWLEC200.Data.ExternalCO2Sensor4")]
        [InlineData("KWLEC200.Data.ExternalCO2Sensor5")]
        [InlineData("KWLEC200.Data.ExternalCO2Sensor6")]
        [InlineData("KWLEC200.Data.ExternalCO2Sensor7")]
        [InlineData("KWLEC200.Data.ExternalCO2Sensor8")]
        [InlineData("KWLEC200.Data.ExternalVOCSensor1")]
        [InlineData("KWLEC200.Data.ExternalVOCSensor2")]
        [InlineData("KWLEC200.Data.ExternalVOCSensor3")]
        [InlineData("KWLEC200.Data.ExternalVOCSensor4")]
        [InlineData("KWLEC200.Data.ExternalVOCSensor5")]
        [InlineData("KWLEC200.Data.ExternalVOCSensor6")]
        [InlineData("KWLEC200.Data.ExternalVOCSensor7")]
        [InlineData("KWLEC200.Data.ExternalVOCSensor8")]
        [InlineData("KWLEC200.Data.TemperatureChannel")]
        [InlineData("KWLEC200.Data.WeeklyProfile")]
        [InlineData("KWLEC200.Data.SerialNumber")]
        [InlineData("KWLEC200.Data.ProductionCode")]
        [InlineData("KWLEC200.Data.SupplyFanSpeed")]
        [InlineData("KWLEC200.Data.ExhaustFanSpeed")]
        [InlineData("KWLEC200.Data.VacationOperation")]
        [InlineData("KWLEC200.Data.VacationVentilationLevel")]
        [InlineData("KWLEC200.Data.VacationStartDate")]
        [InlineData("KWLEC200.Data.VacationEndDate")]
        [InlineData("KWLEC200.Data.VacationInterval")]
        [InlineData("KWLEC200.Data.VacationDuration")]
        [InlineData("KWLEC200.Data.PreheaterType")]
        [InlineData("KWLEC200.Data.KwlFunctionType")]
        [InlineData("KWLEC200.Data.HeaterAfterRunTime")]
        [InlineData("KWLEC200.Data.ExternalContact")]
        [InlineData("KWLEC200.Data.FaultTypeOutput")]
        [InlineData("KWLEC200.Data.FilterChange")]
        [InlineData("KWLEC200.Data.FilterChangeInterval")]
        [InlineData("KWLEC200.Data.FilterChangeRemaining")]
        [InlineData("KWLEC200.Data.BypassRoomTemperature")]
        [InlineData("KWLEC200.Data.BypassOutdoorTemperature")]
        [InlineData("KWLEC200.Data.BypassOutdoorTemperature2")]
        [InlineData("KWLEC200.Data.SupplyLevel")]
        [InlineData("KWLEC200.Data.ExhaustLevel")]
        [InlineData("KWLEC200.Data.FanLevelRegion02")]
        [InlineData("KWLEC200.Data.FanLevelRegion24")]
        [InlineData("KWLEC200.Data.FanLevelRegion46")]
        [InlineData("KWLEC200.Data.FanLevelRegion68")]
        [InlineData("KWLEC200.Data.FanLevelRegion80")]
        [InlineData("KWLEC200.Data.OffsetExhaust")]
        [InlineData("KWLEC200.Data.FanLevelConfiguration")]
        [InlineData("KWLEC200.Data.SensorName1")]
        [InlineData("KWLEC200.Data.SensorName2")]
        [InlineData("KWLEC200.Data.SensorName3")]
        [InlineData("KWLEC200.Data.SensorName4")]
        [InlineData("KWLEC200.Data.SensorName5")]
        [InlineData("KWLEC200.Data.SensorName6")]
        [InlineData("KWLEC200.Data.SensorName7")]
        [InlineData("KWLEC200.Data.SensorName8")]
        [InlineData("KWLEC200.Data.CO2SensorName1")]
        [InlineData("KWLEC200.Data.CO2SensorName2")]
        [InlineData("KWLEC200.Data.CO2SensorName3")]
        [InlineData("KWLEC200.Data.CO2SensorName4")]
        [InlineData("KWLEC200.Data.CO2SensorName5")]
        [InlineData("KWLEC200.Data.CO2SensorName6")]
        [InlineData("KWLEC200.Data.CO2SensorName7")]
        [InlineData("KWLEC200.Data.CO2SensorName8")]
        [InlineData("KWLEC200.Data.VOCSensorName1")]
        [InlineData("KWLEC200.Data.VOCSensorName2")]
        [InlineData("KWLEC200.Data.VOCSensorName3")]
        [InlineData("KWLEC200.Data.VOCSensorName4")]
        [InlineData("KWLEC200.Data.VOCSensorName5")]
        [InlineData("KWLEC200.Data.VOCSensorName6")]
        [InlineData("KWLEC200.Data.VOCSensorName7")]
        [InlineData("KWLEC200.Data.VOCSensorName8")]
        [InlineData("KWLEC200.Data.SoftwareVersion")]
        [InlineData("KWLEC200.Data.OperationMinutesSupply")]
        [InlineData("KWLEC200.Data.OperationMinutesExhaust")]
        [InlineData("KWLEC200.Data.OperationMinutesPreheater")]
        [InlineData("KWLEC200.Data.OperationMinutesAfterheater")]
        [InlineData("KWLEC200.Data.PowerPreheater")]
        [InlineData("KWLEC200.Data.PowerAfterheater")]
        //[InlineData("KWLEC200.Data.ResetFlag")]          ??? ResetFlag returns all zeros.
        [InlineData("KWLEC200.Data.ErrorCode")]
        [InlineData("KWLEC200.Data.WarningCode")]
        [InlineData("KWLEC200.Data.InfoCode")]
        [InlineData("KWLEC200.Data.NumberOfErrors")]
        [InlineData("KWLEC200.Data.NumberOfWarnings")]
        [InlineData("KWLEC200.Data.NumberOfInfos")]
        [InlineData("KWLEC200.Data.Errors")]
        [InlineData("KWLEC200.Data.Warnings")]
        [InlineData("KWLEC200.Data.Infos")]
        [InlineData("KWLEC200.Data.StatusFlags")]
        //[InlineData("KWLEC200.Data.GlobalUpdate")]       ??? GlobalUpdate returns all zeros.
        //[InlineData("KWLEC200.Data.LastError")]          ??? LastError returns all zeros.
        [InlineData("KWLEC200.Data.SensorConfig1")]
        [InlineData("KWLEC200.Data.SensorConfig2")]
        [InlineData("KWLEC200.Data.SensorConfig3")]
        [InlineData("KWLEC200.Data.SensorConfig4")]
        [InlineData("KWLEC200.Data.SensorConfig5")]
        [InlineData("KWLEC200.Data.SensorConfig6")]
        [InlineData("KWLEC200.Data.SensorConfig7")]
        [InlineData("KWLEC200.Data.SensorConfig8")]

        [InlineData("KWLEC200.OverviewData")]
        [InlineData("KWLEC200.OverviewData.Date")]
        [InlineData("KWLEC200.OverviewData.Time")]
        [InlineData("KWLEC200.OverviewData.TemperatureChannel")]
        [InlineData("KWLEC200.OverviewData.TemperatureExhaust")]
        [InlineData("KWLEC200.OverviewData.TemperatureExtract")]
        [InlineData("KWLEC200.OverviewData.TemperatureOutdoor")]
        [InlineData("KWLEC200.OverviewData.TemperaturePostHeater")]
        [InlineData("KWLEC200.OverviewData.TemperaturePreHeater")]
        [InlineData("KWLEC200.OverviewData.TemperatureSupply")]
        [InlineData("KWLEC200.OverviewData.OperationMode")]
        [InlineData("KWLEC200.OverviewData.VentilationLevel")]
        [InlineData("KWLEC200.OverviewData.SupplyLevel")]
        [InlineData("KWLEC200.OverviewData.ExhaustLevel")]
        [InlineData("KWLEC200.OverviewData.VentilationPercentage")]
        [InlineData("KWLEC200.OverviewData.SupplyFanSpeed")]
        [InlineData("KWLEC200.OverviewData.ExhaustFanSpeed")]

        [InlineData("Data.ItemDescription")]
        [InlineData("Data.OrderNumber")]
        [InlineData("Data.MacAddress")]
        [InlineData("Data.Language")]
        [InlineData("Data.Date")]
        [InlineData("Data.Time")]
        [InlineData("Data.DayLightSaving")]
        [InlineData("Data.AutoUpdateEnabled")]
        [InlineData("Data.PortalAccessEnabled")]
        [InlineData("Data.ExhaustVentilatorVoltageLevel1")]
        [InlineData("Data.SupplyVentilatorVoltageLevel1")]
        [InlineData("Data.ExhaustVentilatorVoltageLevel2")]
        [InlineData("Data.SupplyVentilatorVoltageLevel2")]
        [InlineData("Data.ExhaustVentilatorVoltageLevel3")]
        [InlineData("Data.SupplyVentilatorVoltageLevel3")]
        [InlineData("Data.ExhaustVentilatorVoltageLevel4")]
        [InlineData("Data.SupplyVentilatorVoltageLevel4")]
        [InlineData("Data.MinimumVentilationLevel")]
        [InlineData("Data.KwlBeEnabled")]
        [InlineData("Data.KwlBecEnabled")]
        [InlineData("Data.DeviceConfiguration")]
        [InlineData("Data.PreheaterStatus")]
        [InlineData("Data.KwlFTFConfig0")]
        [InlineData("Data.KwlFTFConfig1")]
        [InlineData("Data.KwlFTFConfig2")]
        [InlineData("Data.KwlFTFConfig3")]
        [InlineData("Data.KwlFTFConfig4")]
        [InlineData("Data.KwlFTFConfig5")]
        [InlineData("Data.KwlFTFConfig6")]
        [InlineData("Data.KwlFTFConfig7")]
        [InlineData("Data.HumidityControlStatus")]
        [InlineData("Data.HumidityControlTarget")]
        [InlineData("Data.HumidityControlStep")]
        [InlineData("Data.HumidityControlStop")]
        [InlineData("Data.CO2ControlStatus")]
        [InlineData("Data.CO2ControlTarget")]
        [InlineData("Data.CO2ControlStep")]
        [InlineData("Data.VOCControlStatus")]
        [InlineData("Data.VOCControlTarget")]
        [InlineData("Data.VOCControlStep")]
        [InlineData("Data.ThermalComfortTemperature")]
        [InlineData("Data.TimeZoneOffset")]
        [InlineData("Data.DateFormat")]
        [InlineData("Data.HeatExchangerType")]
        [InlineData("Data.PartyOperationDuration")]
        [InlineData("Data.PartyVentilationLevel")]
        [InlineData("Data.PartyOperationRemaining")]
        [InlineData("Data.PartyOperationActivate")]
        [InlineData("Data.StandbyOperationDuration")]
        [InlineData("Data.StandbyVentilationLevel")]
        [InlineData("Data.StandbyOperationRemaining")]
        [InlineData("Data.StandbyOperationActivate")]
        [InlineData("Data.OperationMode")]
        [InlineData("Data.VentilationLevel")]
        [InlineData("Data.VentilationPercentage")]
        [InlineData("Data.TemperatureOutdoor")]
        [InlineData("Data.TemperatureSupply")]
        [InlineData("Data.TemperatureExhaust")]
        [InlineData("Data.TemperatureExtract")]
        [InlineData("Data.TemperaturePreHeater")]
        [InlineData("Data.TemperaturePostHeater")]
        [InlineData("Data.ExternalHumiditySensor1")]
        [InlineData("Data.ExternalHumiditySensor2")]
        [InlineData("Data.ExternalHumiditySensor3")]
        [InlineData("Data.ExternalHumiditySensor4")]
        [InlineData("Data.ExternalHumiditySensor5")]
        [InlineData("Data.ExternalHumiditySensor6")]
        [InlineData("Data.ExternalHumiditySensor7")]
        [InlineData("Data.ExternalHumiditySensor8")]
        [InlineData("Data.ExternalHumidityTemperature1")]
        [InlineData("Data.ExternalHumidityTemperature2")]
        [InlineData("Data.ExternalHumidityTemperature3")]
        [InlineData("Data.ExternalHumidityTemperature4")]
        [InlineData("Data.ExternalHumidityTemperature5")]
        [InlineData("Data.ExternalHumidityTemperature6")]
        [InlineData("Data.ExternalHumidityTemperature7")]
        [InlineData("Data.ExternalHumidityTemperature8")]
        [InlineData("Data.ExternalCO2Sensor1")]
        [InlineData("Data.ExternalCO2Sensor2")]
        [InlineData("Data.ExternalCO2Sensor3")]
        [InlineData("Data.ExternalCO2Sensor4")]
        [InlineData("Data.ExternalCO2Sensor5")]
        [InlineData("Data.ExternalCO2Sensor6")]
        [InlineData("Data.ExternalCO2Sensor7")]
        [InlineData("Data.ExternalCO2Sensor8")]
        [InlineData("Data.ExternalVOCSensor1")]
        [InlineData("Data.ExternalVOCSensor2")]
        [InlineData("Data.ExternalVOCSensor3")]
        [InlineData("Data.ExternalVOCSensor4")]
        [InlineData("Data.ExternalVOCSensor5")]
        [InlineData("Data.ExternalVOCSensor6")]
        [InlineData("Data.ExternalVOCSensor7")]
        [InlineData("Data.ExternalVOCSensor8")]
        [InlineData("Data.TemperatureChannel")]
        [InlineData("Data.WeeklyProfile")]
        [InlineData("Data.SerialNumber")]
        [InlineData("Data.ProductionCode")]
        [InlineData("Data.SupplyFanSpeed")]
        [InlineData("Data.ExhaustFanSpeed")]
        [InlineData("Data.VacationOperation")]
        [InlineData("Data.VacationVentilationLevel")]
        [InlineData("Data.VacationStartDate")]
        [InlineData("Data.VacationEndDate")]
        [InlineData("Data.VacationInterval")]
        [InlineData("Data.VacationDuration")]
        [InlineData("Data.PreheaterType")]
        [InlineData("Data.KwlFunctionType")]
        [InlineData("Data.HeaterAfterRunTime")]
        [InlineData("Data.ExternalContact")]
        [InlineData("Data.FaultTypeOutput")]
        [InlineData("Data.FilterChange")]
        [InlineData("Data.FilterChangeInterval")]
        [InlineData("Data.FilterChangeRemaining")]
        [InlineData("Data.BypassRoomTemperature")]
        [InlineData("Data.BypassOutdoorTemperature")]
        [InlineData("Data.BypassOutdoorTemperature2")]
        [InlineData("Data.SupplyLevel")]
        [InlineData("Data.ExhaustLevel")]
        [InlineData("Data.FanLevelRegion02")]
        [InlineData("Data.FanLevelRegion24")]
        [InlineData("Data.FanLevelRegion46")]
        [InlineData("Data.FanLevelRegion68")]
        [InlineData("Data.FanLevelRegion80")]
        [InlineData("Data.OffsetExhaust")]
        [InlineData("Data.FanLevelConfiguration")]
        [InlineData("Data.SensorName1")]
        [InlineData("Data.SensorName2")]
        [InlineData("Data.SensorName3")]
        [InlineData("Data.SensorName4")]
        [InlineData("Data.SensorName5")]
        [InlineData("Data.SensorName6")]
        [InlineData("Data.SensorName7")]
        [InlineData("Data.SensorName8")]
        [InlineData("Data.CO2SensorName1")]
        [InlineData("Data.CO2SensorName2")]
        [InlineData("Data.CO2SensorName3")]
        [InlineData("Data.CO2SensorName4")]
        [InlineData("Data.CO2SensorName5")]
        [InlineData("Data.CO2SensorName6")]
        [InlineData("Data.CO2SensorName7")]
        [InlineData("Data.CO2SensorName8")]
        [InlineData("Data.VOCSensorName1")]
        [InlineData("Data.VOCSensorName2")]
        [InlineData("Data.VOCSensorName3")]
        [InlineData("Data.VOCSensorName4")]
        [InlineData("Data.VOCSensorName5")]
        [InlineData("Data.VOCSensorName6")]
        [InlineData("Data.VOCSensorName7")]
        [InlineData("Data.VOCSensorName8")]
        [InlineData("Data.SoftwareVersion")]
        [InlineData("Data.OperationMinutesSupply")]
        [InlineData("Data.OperationMinutesExhaust")]
        [InlineData("Data.OperationMinutesPreheater")]
        [InlineData("Data.OperationMinutesAfterheater")]
        [InlineData("Data.PowerPreheater")]
        [InlineData("Data.PowerAfterheater")]
        //[InlineData("Data.ResetFlag")]          ??? ResetFlag returns all zeros.
        [InlineData("Data.ErrorCode")]
        [InlineData("Data.WarningCode")]
        [InlineData("Data.InfoCode")]
        [InlineData("Data.NumberOfErrors")]
        [InlineData("Data.NumberOfWarnings")]
        [InlineData("Data.NumberOfInfos")]
        [InlineData("Data.Errors")]
        [InlineData("Data.Warnings")]
        [InlineData("Data.Infos")]
        [InlineData("Data.StatusFlags")]
        //[InlineData("Data.GlobalUpdate")]       ??? GlobalUpdate returns all zeros.
        //[InlineData("Data.LastError")]          ??? LastError returns all zeros.
        [InlineData("Data.SensorConfig1")]
        [InlineData("Data.SensorConfig2")]
        [InlineData("Data.SensorConfig3")]
        [InlineData("Data.SensorConfig4")]
        [InlineData("Data.SensorConfig5")]
        [InlineData("Data.SensorConfig6")]
        [InlineData("Data.SensorConfig7")]
        [InlineData("Data.SensorConfig8")]

        [InlineData("OverviewData.Date")]
        [InlineData("OverviewData.Time")]
        [InlineData("OverviewData.TemperatureChannel")]
        [InlineData("OverviewData.TemperatureExhaust")]
        [InlineData("OverviewData.TemperatureExtract")]
        [InlineData("OverviewData.TemperatureOutdoor")]
        [InlineData("OverviewData.TemperaturePostHeater")]
        [InlineData("OverviewData.TemperaturePreHeater")]
        [InlineData("OverviewData.TemperatureSupply")]
        [InlineData("OverviewData.OperationMode")]
        [InlineData("OverviewData.VentilationLevel")]
        [InlineData("OverviewData.SupplyLevel")]
        [InlineData("OverviewData.ExhaustLevel")]
        [InlineData("OverviewData.VentilationPercentage")]
        [InlineData("OverviewData.SupplyFanSpeed")]
        [InlineData("OverviewData.ExhaustFanSpeed")]
        public void TestProperty(string property)
        {
            Assert.True(KWLEC200.IsProperty(property));
            Assert.NotNull(_kwlec200.GetPropertyValue(property));
        }

        #endregion
    }
}
