// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TestData.cs" company="DTV-Online">
//   Copyright(c) 2018 Dr. Peter Trimmel. All rights reserved.
// </copyright>
// <license>
// Licensed under the MIT license. See the LICENSE file in the project root for more information.
// </license>
// --------------------------------------------------------------------------------------------------------------------
namespace EM300LRTest
{
    #region Using Directives

    using System.Globalization;

    using Microsoft.Extensions.Logging;

    using Xunit;
    using Xunit.Abstractions;
    using Xunit.Logger;

    using EM300LRLib;
    using System.Threading.Tasks;

    #endregion Using Directives

    /// <summary>
    /// XUnit testing class.
    /// </summary>
    [Collection("EM300LR Test Collection")]
    public class TestData : IClassFixture<EM300LRFixture>
    {
        #region Private Data Members

        private readonly ILogger<EM300LR> _logger;
        private readonly IEM300LR _em300lr;

        #endregion Private Data Members

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        /// <param name="outputHelper"></param>
        public TestData(EM300LRFixture fixture, ITestOutputHelper outputHelper)
        {
            // Set the default culture.
            CultureInfo.CurrentCulture = new CultureInfo("en-US");

            var loggerFactory = new LoggerFactory();
            loggerFactory.AddProvider(new XunitLoggerProvider(outputHelper));
            _logger = loggerFactory.CreateLogger<EM300LR>();

            _em300lr = fixture.EM300LR;
        }

        #endregion Constructors

        #region Test Methods

        [Fact]
        public void TestBControlData()
        {
            Assert.True(_em300lr.Data.IsGood);
            Assert.True(_em300lr.IsInitialized);
        }

        [Theory]
        [InlineData("EM300LR")]
        [InlineData("EM300LR.Data")]
        [InlineData("EM300LR.Data.ActivePowerPlus")]
        [InlineData("EM300LR.Data.ActiveEnergyPlus")]
        [InlineData("EM300LR.Data.ActivePowerMinus")]
        [InlineData("EM300LR.Data.ActiveEnergyMinus")]
        [InlineData("EM300LR.Data.ReactivePowerPlus")]
        [InlineData("EM300LR.Data.ReactiveEnergyPlus")]
        [InlineData("EM300LR.Data.ReactivePowerMinus")]
        [InlineData("EM300LR.Data.ReactiveEnergyMinus")]
        [InlineData("EM300LR.Data.ApparentPowerPlus")]
        [InlineData("EM300LR.Data.ApparentEnergyPlus")]
        [InlineData("EM300LR.Data.ApparentPowerMinus")]
        [InlineData("EM300LR.Data.ApparentEnergyMinus")]
        [InlineData("EM300LR.Data.PowerFactor")]
        [InlineData("EM300LR.Data.SupplyFrequency")]
        [InlineData("EM300LR.Data.ActivePowerPlusL1")]
        [InlineData("EM300LR.Data.ActiveEnergyPlusL1")]
        [InlineData("EM300LR.Data.ActivePowerMinusL1")]
        [InlineData("EM300LR.Data.ActiveEnergyMinusL1")]
        [InlineData("EM300LR.Data.ReactivePowerPlusL1")]
        [InlineData("EM300LR.Data.ReactiveEnergyPlusL1")]
        [InlineData("EM300LR.Data.ReactivePowerMinusL1")]
        [InlineData("EM300LR.Data.ReactiveEnergyMinusL1")]
        [InlineData("EM300LR.Data.ApparentPowerPlusL1")]
        [InlineData("EM300LR.Data.ApparentEnergyPlusL1")]
        [InlineData("EM300LR.Data.ApparentPowerMinusL1")]
        [InlineData("EM300LR.Data.ApparentEnergyMinusL1")]
        [InlineData("EM300LR.Data.CurrentL1")]
        [InlineData("EM300LR.Data.VoltageL1")]
        [InlineData("EM300LR.Data.PowerFactorL1")]
        [InlineData("EM300LR.Data.ActivePowerPlusL2")]
        [InlineData("EM300LR.Data.ActiveEnergyPlusL2")]
        [InlineData("EM300LR.Data.ActivePowerMinusL2")]
        [InlineData("EM300LR.Data.ActiveEnergyMinusL2")]
        [InlineData("EM300LR.Data.ReactivePowerPlusL2")]
        [InlineData("EM300LR.Data.ReactiveEnergyPlusL2")]
        [InlineData("EM300LR.Data.ReactivePowerMinusL2")]
        [InlineData("EM300LR.Data.ReactiveEnergyMinusL2")]
        [InlineData("EM300LR.Data.ApparentPowerPlusL2")]
        [InlineData("EM300LR.Data.ApparentEnergyPlusL2")]
        [InlineData("EM300LR.Data.ApparentPowerMinusL2")]
        [InlineData("EM300LR.Data.ApparentEnergyMinusL2")]
        [InlineData("EM300LR.Data.CurrentL2")]
        [InlineData("EM300LR.Data.VoltageL2")]
        [InlineData("EM300LR.Data.PowerFactorL2")]
        [InlineData("EM300LR.Data.ActivePowerPlusL3")]
        [InlineData("EM300LR.Data.ActiveEnergyPlusL3")]
        [InlineData("EM300LR.Data.ActivePowerMinusL3")]
        [InlineData("EM300LR.Data.ActiveEnergyMinusL3")]
        [InlineData("EM300LR.Data.ReactivePowerPlusL3")]
        [InlineData("EM300LR.Data.ReactiveEnergyPlusL3")]
        [InlineData("EM300LR.Data.ReactivePowerMinusL3")]
        [InlineData("EM300LR.Data.ReactiveEnergyMinusL3")]
        [InlineData("EM300LR.Data.ApparentPowerPlusL3")]
        [InlineData("EM300LR.Data.ApparentEnergyPlusL3")]
        [InlineData("EM300LR.Data.ApparentPowerMinusL3")]
        [InlineData("EM300LR.Data.ApparentEnergyMinusL3")]
        [InlineData("EM300LR.Data.CurrentL3")]
        [InlineData("EM300LR.Data.VoltageL3")]
        [InlineData("EM300LR.Data.PowerFactorL3")]
        [InlineData("EM300LR.TotalData")]
        [InlineData("EM300LR.TotalData.ActivePowerPlus")]
        [InlineData("EM300LR.TotalData.ActiveEnergyPlus")]
        [InlineData("EM300LR.TotalData.ActivePowerMinus")]
        [InlineData("EM300LR.TotalData.ActiveEnergyMinus")]
        [InlineData("EM300LR.TotalData.ReactivePowerPlus")]
        [InlineData("EM300LR.TotalData.ReactiveEnergyPlus")]
        [InlineData("EM300LR.TotalData.ReactivePowerMinus")]
        [InlineData("EM300LR.TotalData.ReactiveEnergyMinus")]
        [InlineData("EM300LR.TotalData.ApparentPowerPlus")]
        [InlineData("EM300LR.TotalData.ApparentEnergyPlus")]
        [InlineData("EM300LR.TotalData.ApparentPowerMinus")]
        [InlineData("EM300LR.TotalData.ApparentEnergyMinus")]
        [InlineData("EM300LR.TotalData.PowerFactor")]
        [InlineData("EM300LR.TotalData.SupplyFrequency")]
        [InlineData("EM300LR.Phase1Data")]
        [InlineData("EM300LR.Phase1Data.ActivePowerPlusL1")]
        [InlineData("EM300LR.Phase1Data.ActiveEnergyPlusL1")]
        [InlineData("EM300LR.Phase1Data.ActivePowerMinusL1")]
        [InlineData("EM300LR.Phase1Data.ActiveEnergyMinusL1")]
        [InlineData("EM300LR.Phase1Data.ReactivePowerPlusL1")]
        [InlineData("EM300LR.Phase1Data.ReactiveEnergyPlusL1")]
        [InlineData("EM300LR.Phase1Data.ReactivePowerMinusL1")]
        [InlineData("EM300LR.Phase1Data.ReactiveEnergyMinusL1")]
        [InlineData("EM300LR.Phase1Data.ApparentPowerPlusL1")]
        [InlineData("EM300LR.Phase1Data.ApparentEnergyPlusL1")]
        [InlineData("EM300LR.Phase1Data.ApparentPowerMinusL1")]
        [InlineData("EM300LR.Phase1Data.ApparentEnergyMinusL1")]
        [InlineData("EM300LR.Phase1Data.CurrentL1")]
        [InlineData("EM300LR.Phase1Data.VoltageL1")]
        [InlineData("EM300LR.Phase1Data.PowerFactorL1")]
        [InlineData("EM300LR.Phase2Data")]
        [InlineData("EM300LR.Phase2Data.ActivePowerPlusL2")]
        [InlineData("EM300LR.Phase2Data.ActiveEnergyPlusL2")]
        [InlineData("EM300LR.Phase2Data.ActivePowerMinusL2")]
        [InlineData("EM300LR.Phase2Data.ActiveEnergyMinusL2")]
        [InlineData("EM300LR.Phase2Data.ReactivePowerPlusL2")]
        [InlineData("EM300LR.Phase2Data.ReactiveEnergyPlusL2")]
        [InlineData("EM300LR.Phase2Data.ReactivePowerMinusL2")]
        [InlineData("EM300LR.Phase2Data.ReactiveEnergyMinusL2")]
        [InlineData("EM300LR.Phase2Data.ApparentPowerPlusL2")]
        [InlineData("EM300LR.Phase2Data.ApparentEnergyPlusL2")]
        [InlineData("EM300LR.Phase2Data.ApparentPowerMinusL2")]
        [InlineData("EM300LR.Phase2Data.ApparentEnergyMinusL2")]
        [InlineData("EM300LR.Phase2Data.CurrentL2")]
        [InlineData("EM300LR.Phase2Data.VoltageL2")]
        [InlineData("EM300LR.Phase2Data.PowerFactorL2")]
        [InlineData("EM300LR.Phase3Data")]
        [InlineData("EM300LR.Phase3Data.ActivePowerPlusL3")]
        [InlineData("EM300LR.Phase3Data.ActiveEnergyPlusL3")]
        [InlineData("EM300LR.Phase3Data.ActivePowerMinusL3")]
        [InlineData("EM300LR.Phase3Data.ActiveEnergyMinusL3")]
        [InlineData("EM300LR.Phase3Data.ReactivePowerPlusL3")]
        [InlineData("EM300LR.Phase3Data.ReactiveEnergyPlusL3")]
        [InlineData("EM300LR.Phase3Data.ReactivePowerMinusL3")]
        [InlineData("EM300LR.Phase3Data.ReactiveEnergyMinusL3")]
        [InlineData("EM300LR.Phase3Data.ApparentPowerPlusL3")]
        [InlineData("EM300LR.Phase3Data.ApparentEnergyPlusL3")]
        [InlineData("EM300LR.Phase3Data.ApparentPowerMinusL3")]
        [InlineData("EM300LR.Phase3Data.ApparentEnergyMinusL3")]
        [InlineData("EM300LR.Phase3Data.CurrentL3")]
        [InlineData("EM300LR.Phase3Data.VoltageL3")]
        [InlineData("EM300LR.Phase3Data.PowerFactorL3")]
        [InlineData("Data")]
        [InlineData("Data.ActivePowerPlus")]
        [InlineData("Data.ActiveEnergyPlus")]
        [InlineData("Data.ActivePowerMinus")]
        [InlineData("Data.ActiveEnergyMinus")]
        [InlineData("Data.ReactivePowerPlus")]
        [InlineData("Data.ReactiveEnergyPlus")]
        [InlineData("Data.ReactivePowerMinus")]
        [InlineData("Data.ReactiveEnergyMinus")]
        [InlineData("Data.ApparentPowerPlus")]
        [InlineData("Data.ApparentEnergyPlus")]
        [InlineData("Data.ApparentPowerMinus")]
        [InlineData("Data.ApparentEnergyMinus")]
        [InlineData("Data.PowerFactor")]
        [InlineData("Data.SupplyFrequency")]
        [InlineData("Data.ActivePowerPlusL1")]
        [InlineData("Data.ActiveEnergyPlusL1")]
        [InlineData("Data.ActivePowerMinusL1")]
        [InlineData("Data.ActiveEnergyMinusL1")]
        [InlineData("Data.ReactivePowerPlusL1")]
        [InlineData("Data.ReactiveEnergyPlusL1")]
        [InlineData("Data.ReactivePowerMinusL1")]
        [InlineData("Data.ReactiveEnergyMinusL1")]
        [InlineData("Data.ApparentPowerPlusL1")]
        [InlineData("Data.ApparentEnergyPlusL1")]
        [InlineData("Data.ApparentPowerMinusL1")]
        [InlineData("Data.ApparentEnergyMinusL1")]
        [InlineData("Data.CurrentL1")]
        [InlineData("Data.VoltageL1")]
        [InlineData("Data.PowerFactorL1")]
        [InlineData("Data.ActivePowerPlusL2")]
        [InlineData("Data.ActiveEnergyPlusL2")]
        [InlineData("Data.ActivePowerMinusL2")]
        [InlineData("Data.ActiveEnergyMinusL2")]
        [InlineData("Data.ReactivePowerPlusL2")]
        [InlineData("Data.ReactiveEnergyPlusL2")]
        [InlineData("Data.ReactivePowerMinusL2")]
        [InlineData("Data.ReactiveEnergyMinusL2")]
        [InlineData("Data.ApparentPowerPlusL2")]
        [InlineData("Data.ApparentEnergyPlusL2")]
        [InlineData("Data.ApparentPowerMinusL2")]
        [InlineData("Data.ApparentEnergyMinusL2")]
        [InlineData("Data.CurrentL2")]
        [InlineData("Data.VoltageL2")]
        [InlineData("Data.PowerFactorL2")]
        [InlineData("Data.ActivePowerPlusL3")]
        [InlineData("Data.ActiveEnergyPlusL3")]
        [InlineData("Data.ActivePowerMinusL3")]
        [InlineData("Data.ActiveEnergyMinusL3")]
        [InlineData("Data.ReactivePowerPlusL3")]
        [InlineData("Data.ReactiveEnergyPlusL3")]
        [InlineData("Data.ReactivePowerMinusL3")]
        [InlineData("Data.ReactiveEnergyMinusL3")]
        [InlineData("Data.ApparentPowerPlusL3")]
        [InlineData("Data.ApparentEnergyPlusL3")]
        [InlineData("Data.ApparentPowerMinusL3")]
        [InlineData("Data.ApparentEnergyMinusL3")]
        [InlineData("Data.CurrentL3")]
        [InlineData("Data.VoltageL3")]
        [InlineData("Data.PowerFactorL3")]
        [InlineData("ActivePowerPlus")]
        [InlineData("ActiveEnergyPlus")]
        [InlineData("ActivePowerMinus")]
        [InlineData("ActiveEnergyMinus")]
        [InlineData("ReactivePowerPlus")]
        [InlineData("ReactiveEnergyPlus")]
        [InlineData("ReactivePowerMinus")]
        [InlineData("ReactiveEnergyMinus")]
        [InlineData("ApparentPowerPlus")]
        [InlineData("ApparentEnergyPlus")]
        [InlineData("ApparentPowerMinus")]
        [InlineData("ApparentEnergyMinus")]
        [InlineData("PowerFactor")]
        [InlineData("SupplyFrequency")]
        [InlineData("ActivePowerPlusL1")]
        [InlineData("ActiveEnergyPlusL1")]
        [InlineData("ActivePowerMinusL1")]
        [InlineData("ActiveEnergyMinusL1")]
        [InlineData("ReactivePowerPlusL1")]
        [InlineData("ReactiveEnergyPlusL1")]
        [InlineData("ReactivePowerMinusL1")]
        [InlineData("ReactiveEnergyMinusL1")]
        [InlineData("ApparentPowerPlusL1")]
        [InlineData("ApparentEnergyPlusL1")]
        [InlineData("ApparentPowerMinusL1")]
        [InlineData("ApparentEnergyMinusL1")]
        [InlineData("CurrentL1")]
        [InlineData("VoltageL1")]
        [InlineData("PowerFactorL1")]
        [InlineData("ActivePowerPlusL2")]
        [InlineData("ActiveEnergyPlusL2")]
        [InlineData("ActivePowerMinusL2")]
        [InlineData("ActiveEnergyMinusL2")]
        [InlineData("ReactivePowerPlusL2")]
        [InlineData("ReactiveEnergyPlusL2")]
        [InlineData("ReactivePowerMinusL2")]
        [InlineData("ReactiveEnergyMinusL2")]
        [InlineData("ApparentPowerPlusL2")]
        [InlineData("ApparentEnergyPlusL2")]
        [InlineData("ApparentPowerMinusL2")]
        [InlineData("ApparentEnergyMinusL2")]
        [InlineData("CurrentL2")]
        [InlineData("VoltageL2")]
        [InlineData("PowerFactorL2")]
        [InlineData("ActivePowerPlusL3")]
        [InlineData("ActiveEnergyPlusL3")]
        [InlineData("ActivePowerMinusL3")]
        [InlineData("ActiveEnergyMinusL3")]
        [InlineData("ReactivePowerPlusL3")]
        [InlineData("ReactiveEnergyPlusL3")]
        [InlineData("ReactivePowerMinusL3")]
        [InlineData("ReactiveEnergyMinusL3")]
        [InlineData("ApparentPowerPlusL3")]
        [InlineData("ApparentEnergyPlusL3")]
        [InlineData("ApparentPowerMinusL3")]
        [InlineData("ApparentEnergyMinusL3")]
        [InlineData("CurrentL3")]
        [InlineData("VoltageL3")]
        [InlineData("PowerFactorL3")]
        [InlineData("TotalData")]
        [InlineData("TotalData.ActivePowerPlus")]
        [InlineData("TotalData.ActiveEnergyPlus")]
        [InlineData("TotalData.ActivePowerMinus")]
        [InlineData("TotalData.ActiveEnergyMinus")]
        [InlineData("TotalData.ReactivePowerPlus")]
        [InlineData("TotalData.ReactiveEnergyPlus")]
        [InlineData("TotalData.ReactivePowerMinus")]
        [InlineData("TotalData.ReactiveEnergyMinus")]
        [InlineData("TotalData.ApparentPowerPlus")]
        [InlineData("TotalData.ApparentEnergyPlus")]
        [InlineData("TotalData.ApparentPowerMinus")]
        [InlineData("TotalData.ApparentEnergyMinus")]
        [InlineData("TotalData.PowerFactor")]
        [InlineData("TotalData.SupplyFrequency")]
        [InlineData("Phase1Data")]
        [InlineData("Phase1Data.ActivePowerPlusL1")]
        [InlineData("Phase1Data.ActiveEnergyPlusL1")]
        [InlineData("Phase1Data.ActivePowerMinusL1")]
        [InlineData("Phase1Data.ActiveEnergyMinusL1")]
        [InlineData("Phase1Data.ReactivePowerPlusL1")]
        [InlineData("Phase1Data.ReactiveEnergyPlusL1")]
        [InlineData("Phase1Data.ReactivePowerMinusL1")]
        [InlineData("Phase1Data.ReactiveEnergyMinusL1")]
        [InlineData("Phase1Data.ApparentPowerPlusL1")]
        [InlineData("Phase1Data.ApparentEnergyPlusL1")]
        [InlineData("Phase1Data.ApparentPowerMinusL1")]
        [InlineData("Phase1Data.ApparentEnergyMinusL1")]
        [InlineData("Phase1Data.CurrentL1")]
        [InlineData("Phase1Data.VoltageL1")]
        [InlineData("Phase1Data.PowerFactorL1")]
        [InlineData("Phase2Data")]
        [InlineData("Phase2Data.ActivePowerPlusL2")]
        [InlineData("Phase2Data.ActiveEnergyPlusL2")]
        [InlineData("Phase2Data.ActivePowerMinusL2")]
        [InlineData("Phase2Data.ActiveEnergyMinusL2")]
        [InlineData("Phase2Data.ReactivePowerPlusL2")]
        [InlineData("Phase2Data.ReactiveEnergyPlusL2")]
        [InlineData("Phase2Data.ReactivePowerMinusL2")]
        [InlineData("Phase2Data.ReactiveEnergyMinusL2")]
        [InlineData("Phase2Data.ApparentPowerPlusL2")]
        [InlineData("Phase2Data.ApparentEnergyPlusL2")]
        [InlineData("Phase2Data.ApparentPowerMinusL2")]
        [InlineData("Phase2Data.ApparentEnergyMinusL2")]
        [InlineData("Phase2Data.CurrentL2")]
        [InlineData("Phase2Data.VoltageL2")]
        [InlineData("Phase2Data.PowerFactorL2")]
        [InlineData("Phase3Data")]
        [InlineData("Phase3Data.ActivePowerPlusL3")]
        [InlineData("Phase3Data.ActiveEnergyPlusL3")]
        [InlineData("Phase3Data.ActivePowerMinusL3")]
        [InlineData("Phase3Data.ActiveEnergyMinusL3")]
        [InlineData("Phase3Data.ReactivePowerPlusL3")]
        [InlineData("Phase3Data.ReactiveEnergyPlusL3")]
        [InlineData("Phase3Data.ReactivePowerMinusL3")]
        [InlineData("Phase3Data.ReactiveEnergyMinusL3")]
        [InlineData("Phase3Data.ApparentPowerPlusL3")]
        [InlineData("Phase3Data.ApparentEnergyPlusL3")]
        [InlineData("Phase3Data.ApparentPowerMinusL3")]
        [InlineData("Phase3Data.ApparentEnergyMinusL3")]
        [InlineData("Phase3Data.CurrentL3")]
        [InlineData("Phase3Data.VoltageL3")]
        [InlineData("Phase3Data.PowerFactorL3")]
        public void TestProperty(string property)
        {
            Assert.True(EM300LR.IsProperty(property));
            Assert.NotNull(_em300lr.GetPropertyValue(property));
        }

        #endregion Test Methods
    }
}