// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TestData.cs" company="DTV-Online">
//   Copyright(c) 2018 Dr. Peter Trimmel. All rights reserved.
// </copyright>
// <license>
// Licensed under the MIT license. See the LICENSE file in the project root for more information.
// </license>
// --------------------------------------------------------------------------------------------------------------------
namespace ETAPU11Test
{
    #region Using Directives

    using System.Globalization;

    using Microsoft.Extensions.Logging;

    using Xunit;
    using Xunit.Abstractions;
    using Xunit.Logger;

    using ETAPU11Lib;

    #endregion

    /// <summary>
    /// XUnit testing class.
    /// </summary>
    [Collection("ETAPU11 Test Collection")]
    public class TestData : IClassFixture<ETAPU11Fixture>
    {
        #region Private Data Members

        private readonly ILogger<ETAPU11> _logger;
        private readonly IETAPU11 _etapu11;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        /// <param name="outputHelper"></param>
        public TestData(ETAPU11Fixture fixture, ITestOutputHelper outputHelper)
        {
            // Set the default culture.
            CultureInfo.CurrentCulture = new CultureInfo("en-US");

            var loggerFactory = new LoggerFactory();
            loggerFactory.AddProvider(new XunitLoggerProvider(outputHelper));
            _logger = loggerFactory.CreateLogger<ETAPU11>();

            _etapu11 = fixture.ETAPU11;
        }

        #endregion

        #region Test Methods

        [Theory]
        [InlineData("ETAPU11")]
        [InlineData("ETAPU11.Data")]
        [InlineData("ETAPU11.Data.FullLoadHours")]
        [InlineData("ETAPU11.Data.TotalConsumed")]
        [InlineData("ETAPU11.Data.BoilerState")]
        [InlineData("ETAPU11.Data.BoilerPressure")]
        [InlineData("ETAPU11.Data.BoilerTemperature")]
        [InlineData("ETAPU11.Data.BoilerTarget")]
        [InlineData("ETAPU11.Data.BoilerBottom")]
        [InlineData("ETAPU11.Data.FlowControlState")]
        [InlineData("ETAPU11.Data.DiverterValveState")]
        [InlineData("ETAPU11.Data.DiverterValveDemand")]
        [InlineData("ETAPU11.Data.DemandedOutput")]
        [InlineData("ETAPU11.Data.FlowMixValveTarget")]
        [InlineData("ETAPU11.Data.FlowMixValveState")]
        [InlineData("ETAPU11.Data.FlowMixValveCurrTemp")]
        [InlineData("ETAPU11.Data.FlowMixValvePosition")]
        [InlineData("ETAPU11.Data.BoilerPumpOutput")]
        [InlineData("ETAPU11.Data.BoilerPumpDemand")]
        [InlineData("ETAPU11.Data.FlueGasTemperature")]
        [InlineData("ETAPU11.Data.DraughtFanSpeed")]
        [InlineData("ETAPU11.Data.ResidualO2")]
        [InlineData("ETAPU11.Data.StokerScrewDemand")]
        [InlineData("ETAPU11.Data.StokerScrewClockRate")]
        [InlineData("ETAPU11.Data.StokerScrewState")]
        [InlineData("ETAPU11.Data.StokerScrewMotorCurr")]
        [InlineData("ETAPU11.Data.AshRemovalState")]
        [InlineData("ETAPU11.Data.AshRemovalStartIdleTime")]
        [InlineData("ETAPU11.Data.AshRemovalDurationIdleTime")]
        [InlineData("ETAPU11.Data.ConsumptionSinceDeAsh")]
        [InlineData("ETAPU11.Data.ConsumptionSinceAshBoxEmptied")]
        [InlineData("ETAPU11.Data.EmptyAshBoxAfter")]
        [InlineData("ETAPU11.Data.ConsumptionSinceMaintainence")]
        [InlineData("ETAPU11.Data.HopperState")]
        [InlineData("ETAPU11.Data.HopperFillUpPelletBin")]
        [InlineData("ETAPU11.Data.HopperPelletBinContents")]
        [InlineData("ETAPU11.Data.HopperFillUpTime")]
        [InlineData("ETAPU11.Data.HopperVacuumState")]
        [InlineData("ETAPU11.Data.HopperVacuumDemand")]
        [InlineData("ETAPU11.Data.OnOffButton")]
        [InlineData("ETAPU11.Data.DeAshButton")]
        [InlineData("ETAPU11.Data.HotwaterTankState")]
        [InlineData("ETAPU11.Data.ChargingTimesState")]
        [InlineData("ETAPU11.Data.ChargingTimesSwitchStatus")]
        [InlineData("ETAPU11.Data.ChargingTimesTemperature")]
        [InlineData("ETAPU11.Data.HotwaterSwitchonDiff")]
        [InlineData("ETAPU11.Data.HotwaterTarget")]
        [InlineData("ETAPU11.Data.HotwaterTemperature")]
        [InlineData("ETAPU11.Data.ChargeButton")]
        [InlineData("ETAPU11.Data.RoomSensor")]
        [InlineData("ETAPU11.Data.HeatingCircuitState")]
        [InlineData("ETAPU11.Data.RunningState")]
        [InlineData("ETAPU11.Data.HeatingTimes")]
        [InlineData("ETAPU11.Data.HeatingSwitchStatus")]
        [InlineData("ETAPU11.Data.HeatingTemperature")]
        [InlineData("ETAPU11.Data.RoomTemperature")]
        [InlineData("ETAPU11.Data.RoomTarget")]
        [InlineData("ETAPU11.Data.Flow")]
        [InlineData("ETAPU11.Data.HeatingCurve")]
        [InlineData("ETAPU11.Data.FlowAtMinus10")]
        [InlineData("ETAPU11.Data.FlowAtPlus10")]
        [InlineData("ETAPU11.Data.FlowSetBack")]
        [InlineData("ETAPU11.Data.OutsideTemperatureDelayed")]
        [InlineData("ETAPU11.Data.DayHeatingThreshold")]
        [InlineData("ETAPU11.Data.NightHeatingThreshold")]
        [InlineData("ETAPU11.Data.HeatingDayButton")]
        [InlineData("ETAPU11.Data.HeatingAutoButton")]
        [InlineData("ETAPU11.Data.HeatingNightButton")]
        [InlineData("ETAPU11.Data.HeatingOnOffButton")]
        [InlineData("ETAPU11.Data.HeatingHomeButton")]
        [InlineData("ETAPU11.Data.HeatingAwayButton")]
        [InlineData("ETAPU11.Data.HeatingHolidayStart")]
        [InlineData("ETAPU11.Data.HeatingHolidayEnd")]
        [InlineData("ETAPU11.Data.DischargeScrewDemand")]
        [InlineData("ETAPU11.Data.DischargeScrewClockRate")]
        [InlineData("ETAPU11.Data.DischargeScrewState")]
        [InlineData("ETAPU11.Data.DischargeScrewMotorCurr")]
        [InlineData("ETAPU11.Data.ConveyingSystem")]
        [InlineData("ETAPU11.Data.Stock")]
        [InlineData("ETAPU11.Data.StockWarningLimit")]
        [InlineData("ETAPU11.Data.OutsideTemperature")]
        [InlineData("ETAPU11.Data.FirebedState")]
        [InlineData("ETAPU11.Data.SupplyDemand")]
        [InlineData("ETAPU11.Data.IgnitionDemand")]
        [InlineData("ETAPU11.Data.FlowMixValveTemperature")]
        [InlineData("ETAPU11.Data.AirValveSetPosition")]
        [InlineData("ETAPU11.Data.AirValveCurrPosition")]

        [InlineData("ETAPU11.BoilerData")]
        [InlineData("ETAPU11.BoilerData.FullLoadHours")]
        [InlineData("ETAPU11.BoilerData.TotalConsumed")]
        [InlineData("ETAPU11.BoilerData.ConsumptionSinceDeAsh")]
        [InlineData("ETAPU11.BoilerData.ConsumptionSinceAshBoxEmptied")]
        [InlineData("ETAPU11.BoilerData.ConsumptionSinceMaintainence")]
        [InlineData("ETAPU11.BoilerData.HopperFillUpPelletBin")]
        [InlineData("ETAPU11.BoilerData.HopperPelletBinContents")]
        [InlineData("ETAPU11.BoilerData.HopperFillUpTime")]
        [InlineData("ETAPU11.BoilerData.BoilerState")]
        [InlineData("ETAPU11.BoilerData.BoilerPressure")]
        [InlineData("ETAPU11.BoilerData.BoilerTemperature")]
        [InlineData("ETAPU11.BoilerData.BoilerTarget")]
        [InlineData("ETAPU11.BoilerData.BoilerBottom")]
        [InlineData("ETAPU11.BoilerData.FlueGasTemperature")]
        [InlineData("ETAPU11.BoilerData.DraughtFanSpeed")]
        [InlineData("ETAPU11.BoilerData.ResidualO2")]

        [InlineData("ETAPU11.HotwaterData")]
        [InlineData("ETAPU11.HotwaterData.HotwaterTankState")]
        [InlineData("ETAPU11.HotwaterData.ChargingTimesState")]
        [InlineData("ETAPU11.HotwaterData.ChargingTimesSwitchStatus")]
        [InlineData("ETAPU11.HotwaterData.ChargingTimesTemperature")]
        [InlineData("ETAPU11.HotwaterData.HotwaterSwitchonDiff")]
        [InlineData("ETAPU11.HotwaterData.HotwaterTarget")]
        [InlineData("ETAPU11.HotwaterData.HotwaterTemperature")]

        [InlineData("ETAPU11.HeatingData")]
        [InlineData("ETAPU11.HeatingData.RoomSensor")]
        [InlineData("ETAPU11.HeatingData.HeatingCircuitState")]
        [InlineData("ETAPU11.HeatingData.RunningState")]
        [InlineData("ETAPU11.HeatingData.HeatingTimes")]
        [InlineData("ETAPU11.HeatingData.HeatingSwitchStatus")]
        [InlineData("ETAPU11.HeatingData.HeatingTemperature")]
        [InlineData("ETAPU11.HeatingData.RoomTemperature")]
        [InlineData("ETAPU11.HeatingData.RoomTarget")]
        [InlineData("ETAPU11.HeatingData.Flow")]
        [InlineData("ETAPU11.HeatingData.DayHeatingThreshold")]
        [InlineData("ETAPU11.HeatingData.NightHeatingThreshold")]

        [InlineData("ETAPU11.StorageData")]
        [InlineData("ETAPU11.StorageData.DischargeScrewDemand")]
        [InlineData("ETAPU11.StorageData.DischargeScrewState")]
        [InlineData("ETAPU11.StorageData.DischargeScrewMotorCurr")]
        [InlineData("ETAPU11.StorageData.ConveyingSystem")]
        [InlineData("ETAPU11.StorageData.Stock")]
        [InlineData("ETAPU11.StorageData.StockWarningLimit")]
        [InlineData("ETAPU11.SystemData.OutsideTemperature")]

        [InlineData("Data")]
        [InlineData("Data.FullLoadHours")]
        [InlineData("Data.TotalConsumed")]
        [InlineData("Data.BoilerState")]
        [InlineData("Data.BoilerPressure")]
        [InlineData("Data.BoilerTemperature")]
        [InlineData("Data.BoilerTarget")]
        [InlineData("Data.BoilerBottom")]
        [InlineData("Data.FlowControlState")]
        [InlineData("Data.DiverterValveState")]
        [InlineData("Data.DiverterValveDemand")]
        [InlineData("Data.DemandedOutput")]
        [InlineData("Data.FlowMixValveTarget")]
        [InlineData("Data.FlowMixValveState")]
        [InlineData("Data.FlowMixValveCurrTemp")]
        [InlineData("Data.FlowMixValvePosition")]
        [InlineData("Data.BoilerPumpOutput")]
        [InlineData("Data.BoilerPumpDemand")]
        [InlineData("Data.FlueGasTemperature")]
        [InlineData("Data.DraughtFanSpeed")]
        [InlineData("Data.ResidualO2")]
        [InlineData("Data.StokerScrewDemand")]
        [InlineData("Data.StokerScrewClockRate")]
        [InlineData("Data.StokerScrewState")]
        [InlineData("Data.StokerScrewMotorCurr")]
        [InlineData("Data.AshRemovalState")]
        [InlineData("Data.AshRemovalStartIdleTime")]
        [InlineData("Data.AshRemovalDurationIdleTime")]
        [InlineData("Data.ConsumptionSinceDeAsh")]
        [InlineData("Data.ConsumptionSinceAshBoxEmptied")]
        [InlineData("Data.EmptyAshBoxAfter")]
        [InlineData("Data.ConsumptionSinceMaintainence")]
        [InlineData("Data.HopperState")]
        [InlineData("Data.HopperFillUpPelletBin")]
        [InlineData("Data.HopperPelletBinContents")]
        [InlineData("Data.HopperFillUpTime")]
        [InlineData("Data.HopperVacuumState")]
        [InlineData("Data.HopperVacuumDemand")]
        [InlineData("Data.OnOffButton")]
        [InlineData("Data.DeAshButton")]
        [InlineData("Data.HotwaterTankState")]
        [InlineData("Data.ChargingTimesState")]
        [InlineData("Data.ChargingTimesSwitchStatus")]
        [InlineData("Data.ChargingTimesTemperature")]
        [InlineData("Data.HotwaterSwitchonDiff")]
        [InlineData("Data.HotwaterTarget")]
        [InlineData("Data.HotwaterTemperature")]
        [InlineData("Data.ChargeButton")]
        [InlineData("Data.RoomSensor")]
        [InlineData("Data.HeatingCircuitState")]
        [InlineData("Data.RunningState")]
        [InlineData("Data.HeatingTimes")]
        [InlineData("Data.HeatingSwitchStatus")]
        [InlineData("Data.HeatingTemperature")]
        [InlineData("Data.RoomTemperature")]
        [InlineData("Data.RoomTarget")]
        [InlineData("Data.Flow")]
        [InlineData("Data.HeatingCurve")]
        [InlineData("Data.FlowAtMinus10")]
        [InlineData("Data.FlowAtPlus10")]
        [InlineData("Data.FlowSetBack")]
        [InlineData("Data.OutsideTemperatureDelayed")]
        [InlineData("Data.DayHeatingThreshold")]
        [InlineData("Data.NightHeatingThreshold")]
        [InlineData("Data.HeatingDayButton")]
        [InlineData("Data.HeatingAutoButton")]
        [InlineData("Data.HeatingNightButton")]
        [InlineData("Data.HeatingOnOffButton")]
        [InlineData("Data.HeatingHomeButton")]
        [InlineData("Data.HeatingAwayButton")]
        [InlineData("Data.HeatingHolidayStart")]
        [InlineData("Data.HeatingHolidayEnd")]
        [InlineData("Data.DischargeScrewDemand")]
        [InlineData("Data.DischargeScrewClockRate")]
        [InlineData("Data.DischargeScrewState")]
        [InlineData("Data.DischargeScrewMotorCurr")]
        [InlineData("Data.ConveyingSystem")]
        [InlineData("Data.Stock")]
        [InlineData("Data.StockWarningLimit")]
        [InlineData("Data.OutsideTemperature")]
        [InlineData("Data.FirebedState")]
        [InlineData("Data.SupplyDemand")]
        [InlineData("Data.IgnitionDemand")]
        [InlineData("Data.FlowMixValveTemperature")]
        [InlineData("Data.AirValveSetPosition")]
        [InlineData("Data.AirValveCurrPosition")]
        [InlineData("BoilerData.FullLoadHours")]
        [InlineData("BoilerData.TotalConsumed")]
        [InlineData("BoilerData.ConsumptionSinceDeAsh")]
        [InlineData("BoilerData.ConsumptionSinceAshBoxEmptied")]
        [InlineData("BoilerData.ConsumptionSinceMaintainence")]
        [InlineData("BoilerData.HopperFillUpPelletBin")]
        [InlineData("BoilerData.HopperPelletBinContents")]
        [InlineData("BoilerData.HopperFillUpTime")]

        [InlineData("BoilerData")]
        [InlineData("BoilerData.BoilerState")]
        [InlineData("BoilerData.BoilerPressure")]
        [InlineData("BoilerData.BoilerTemperature")]
        [InlineData("BoilerData.BoilerTarget")]
        [InlineData("BoilerData.BoilerBottom")]
        [InlineData("BoilerData.FlueGasTemperature")]
        [InlineData("BoilerData.DraughtFanSpeed")]
        [InlineData("BoilerData.ResidualO2")]

        [InlineData("HotwaterData")]
        [InlineData("HotwaterData.HotwaterTankState")]
        [InlineData("HotwaterData.ChargingTimesState")]
        [InlineData("HotwaterData.ChargingTimesSwitchStatus")]
        [InlineData("HotwaterData.ChargingTimesTemperature")]
        [InlineData("HotwaterData.HotwaterSwitchonDiff")]
        [InlineData("HotwaterData.HotwaterTarget")]
        [InlineData("HotwaterData.HotwaterTemperature")]

        [InlineData("HeatingData")]
        [InlineData("HeatingData.RoomSensor")]
        [InlineData("HeatingData.HeatingCircuitState")]
        [InlineData("HeatingData.RunningState")]
        [InlineData("HeatingData.HeatingTimes")]
        [InlineData("HeatingData.HeatingSwitchStatus")]
        [InlineData("HeatingData.HeatingTemperature")]
        [InlineData("HeatingData.RoomTemperature")]
        [InlineData("HeatingData.RoomTarget")]
        [InlineData("HeatingData.Flow")]
        [InlineData("HeatingData.DayHeatingThreshold")]
        [InlineData("HeatingData.NightHeatingThreshold")]

        [InlineData("StorageData")]
        [InlineData("StorageData.DischargeScrewDemand")]
        [InlineData("StorageData.DischargeScrewState")]
        [InlineData("StorageData.DischargeScrewMotorCurr")]
        [InlineData("StorageData.ConveyingSystem")]
        [InlineData("StorageData.Stock")]
        [InlineData("StorageData.StockWarningLimit")]

        [InlineData("SystemData")]
        [InlineData("SystemData.OutsideTemperature")]

        [InlineData("FullLoadHours")]
        [InlineData("TotalConsumed")]
        [InlineData("BoilerState")]
        [InlineData("BoilerPressure")]
        [InlineData("BoilerTemperature")]
        [InlineData("BoilerTarget")]
        [InlineData("BoilerBottom")]
        [InlineData("FlowControlState")]
        [InlineData("DiverterValveState")]
        [InlineData("DiverterValveDemand")]
        [InlineData("DemandedOutput")]
        [InlineData("FlowMixValveTarget")]
        [InlineData("FlowMixValveState")]
        [InlineData("FlowMixValveCurrTemp")]
        [InlineData("FlowMixValvePosition")]
        [InlineData("BoilerPumpOutput")]
        [InlineData("BoilerPumpDemand")]
        [InlineData("FlueGasTemperature")]
        [InlineData("DraughtFanSpeed")]
        [InlineData("ResidualO2")]
        [InlineData("StokerScrewDemand")]
        [InlineData("StokerScrewClockRate")]
        [InlineData("StokerScrewState")]
        [InlineData("StokerScrewMotorCurr")]
        [InlineData("AshRemovalState")]
        [InlineData("AshRemovalStartIdleTime")]
        [InlineData("AshRemovalDurationIdleTime")]
        [InlineData("ConsumptionSinceDeAsh")]
        [InlineData("ConsumptionSinceAshBoxEmptied")]
        [InlineData("EmptyAshBoxAfter")]
        [InlineData("ConsumptionSinceMaintainence")]
        [InlineData("HopperState")]
        [InlineData("HopperFillUpPelletBin")]
        [InlineData("HopperPelletBinContents")]
        [InlineData("HopperFillUpTime")]
        [InlineData("HopperVacuumState")]
        [InlineData("HopperVacuumDemand")]
        [InlineData("OnOffButton")]
        [InlineData("DeAshButton")]
        [InlineData("HotwaterTankState")]
        [InlineData("ChargingTimesState")]
        [InlineData("ChargingTimesSwitchStatus")]
        [InlineData("ChargingTimesTemperature")]
        [InlineData("HotwaterSwitchonDiff")]
        [InlineData("HotwaterTarget")]
        [InlineData("HotwaterTemperature")]
        [InlineData("ChargeButton")]
        [InlineData("RoomSensor")]
        [InlineData("HeatingCircuitState")]
        [InlineData("RunningState")]
        [InlineData("HeatingTimes")]
        [InlineData("HeatingSwitchStatus")]
        [InlineData("HeatingTemperature")]
        [InlineData("RoomTemperature")]
        [InlineData("RoomTarget")]
        [InlineData("Flow")]
        [InlineData("HeatingCurve")]
        [InlineData("FlowAtMinus10")]
        [InlineData("FlowAtPlus10")]
        [InlineData("FlowSetBack")]
        [InlineData("OutsideTemperatureDelayed")]
        [InlineData("DayHeatingThreshold")]
        [InlineData("NightHeatingThreshold")]
        [InlineData("HeatingDayButton")]
        [InlineData("HeatingAutoButton")]
        [InlineData("HeatingNightButton")]
        [InlineData("HeatingOnOffButton")]
        [InlineData("HeatingHomeButton")]
        [InlineData("HeatingAwayButton")]
        [InlineData("HeatingHolidayStart")]
        [InlineData("HeatingHolidayEnd")]
        [InlineData("DischargeScrewDemand")]
        [InlineData("DischargeScrewClockRate")]
        [InlineData("DischargeScrewState")]
        [InlineData("DischargeScrewMotorCurr")]
        [InlineData("ConveyingSystem")]
        [InlineData("Stock")]
        [InlineData("StockWarningLimit")]
        [InlineData("OutsideTemperature")]
        [InlineData("FirebedState")]
        [InlineData("SupplyDemand")]
        [InlineData("IgnitionDemand")]
        [InlineData("FlowMixValveTemperature")]
        [InlineData("AirValveSetPosition")]
        [InlineData("AirValveCurrPosition")]
        public void TestProperty(string property)
        {
            Assert.True(ETAPU11.IsProperty(property));
            Assert.NotNull(_etapu11.GetPropertyValue(property));
        }

        #endregion
    }
}
